import {
  Challenge,
  ChallengeRequest,
  Credential,
  PAYMENT_CREDENTIAL_HEADER,
  PAYMENT_HEADER_PREFIX,
  PaymentMethod,
  PineLabsOnlineServerConfig,
  VerificationResult,
} from "../types";
import { decodeJson, encodeJson, isBase64Url } from "../utils/base64url";
import { computeChallengeId, deriveChallengeHmacKey } from "../utils/hmac";
import { asRecord, stringOrUndefined } from "../utils/parsers";
import { validateConfig } from "../utils/validation";

export class CredentialVerifier {
  private readonly secretKey: string;
  private readonly realm: string;
  private readonly availablePaymentMethods: PaymentMethod[];

  constructor(config: PineLabsOnlineServerConfig) {
    validateConfig(config);
    this.secretKey = deriveChallengeHmacKey(config.clientSecret);
    this.realm = config.realm ?? config.env;
    this.availablePaymentMethods = [...config.availablePaymentMethods];
  }

  /** Decode and validate a `P3P-Credential: Payment <payload>` header value. */
  async verify(credentialHeader?: string): Promise<VerificationResult> {
    const encoded = extractPayload(credentialHeader ?? "");
    if (!encoded) {
      return { valid: false, error: `Invalid ${PAYMENT_CREDENTIAL_HEADER} header format. Expected: Payment <base64url>` };
    }
    let credential: Credential;
    try {
      credential = dictToCredential(decodeJson(encoded));
    } catch {
      return { valid: false, error: `Failed to decode credential from ${PAYMENT_CREDENTIAL_HEADER} header` };
    }

    const challenge = credential.challenge;
    if (!challenge.id || !challenge.realm || !challenge.request) {
      return { valid: false, credential, error: "Credential contains an incomplete challenge" };
    }
    if (challenge.realm !== this.realm) {
      return { valid: false, credential, error: `Challenge realm mismatch. Expected "${this.realm}", got "${challenge.realm}"` };
    }
    if (!challenge.request.availablePaymentMethods.length) {
      return { valid: false, credential, error: "Challenge missing available payment methods" };
    }
    if (!Number.isFinite(Date.parse(challenge.expires)) || Date.parse(challenge.expires) <= Date.now()) {
      return { valid: false, credential, error: "Challenge has expired" };
    }

    const expectedId = await computeChallengeId(
      this.secretKey,
      challenge.realm,
      challenge.intent,
      encodeJson(challenge.request),
      challenge.expires,
    );
    const { timingSafeEqual } = await import("node:crypto");
    const idBuf = Buffer.from(challenge.id);
    const expectedBuf = Buffer.from(expectedId);
    if (idBuf.length !== expectedBuf.length || !timingSafeEqual(idBuf, expectedBuf)) {
      return {
        valid: false,
        credential,
        error: "Challenge HMAC verification failed. The challenge was not generated by this server.",
      };
    }
    if (!credential.payload?.token) {
      return { valid: false, credential, error: "Credential missing payment token" };
    }
    if (!credential.payload.payment_method) {
      return { valid: false, credential, error: "Credential missing selected payment method" };
    }
    if (
      !challenge.request.availablePaymentMethods.includes(credential.payload.payment_method)
      || !this.availablePaymentMethods.includes(credential.payload.payment_method)
    ) {
      return {
        valid: false,
        credential,
        error: `Selected payment method ${credential.payload.payment_method} is not accepted by this server challenge`,
      };
    }
    return { valid: true, credential };
  }
}

function dictToCredential(raw: unknown): Credential {
  const record = asRecord(raw) ?? {};
  const challenge = asRecord(record.challenge) ?? {};
  const request = asRecord(challenge.request) ?? {};
  const payload = asRecord(record.payload) ?? {};
  const challengeRequest: ChallengeRequest = {
    scheme: String(request.scheme ?? ""),
    amount: String(request.amount ?? ""),
    currency: String(request.currency ?? ""),
    resource: String(request.resource ?? ""),
    availablePaymentMethods: parsePaymentMethods(request.availablePaymentMethods ?? request.available_payment_methods),
  };
  return {
    challenge: {
      id: String(challenge.id ?? ""),
      realm: String(challenge.realm ?? ""),
      paymentGateway: parsePaymentGateway(challenge.paymentGateway ?? challenge.payment_gateway),
      intent: String(challenge.intent ?? ""),
      request: challengeRequest,
      expires: String(challenge.expires ?? ""),
    } satisfies Challenge,
    source: String(record.source ?? ""),
    payload: {
      type: "token",
      token: String(payload.token ?? ""),
      payment_method_reference_id: stringOrUndefined(payload.payment_method_reference_id ?? payload.paymentMethodReferenceId),
      mobile_number: stringOrUndefined(payload.mobile_number ?? payload.mobileNumber),
      payment_method: parsePaymentMethod(payload.payment_method ?? payload.paymentMethod),
    },
  };
}

function parsePaymentGateway(value: unknown): Challenge["paymentGateway"] {
  return value === undefined || value === null ? undefined : String(value) as Challenge["paymentGateway"];
}

function parsePaymentMethod(value: unknown): PaymentMethod {
  if (value === PaymentMethod.RESERVE_PAY || value === PaymentMethod.CARD || value === PaymentMethod.CREDIT_EMI || value === PaymentMethod.Crypto) {
    return value;
  }
  if (value === PaymentMethod.OTM) {
    return PaymentMethod.OTM;
  }
  return String(value ?? "") as PaymentMethod;
}

function parsePaymentMethods(value: unknown): PaymentMethod[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.map(parsePaymentMethod);
}

function extractPayload(header: string): string | undefined {
  const trimmed = header.trim();
  if (!trimmed.startsWith(PAYMENT_HEADER_PREFIX)) {
    return undefined;
  }
  const payload = trimmed.slice(PAYMENT_HEADER_PREFIX.length).trim();
  return isBase64Url(payload) ? payload : undefined;
}
