import { DEFAULT_REALM } from "../config";
import {
  Challenge,
  Credential,
  PAYMENT_HEADER_PREFIX,
  PluralSellerConfig,
  VerificationResult,
} from "../types";
import { decodeJson, encodeJson, isBase64Url } from "../utils/base64url";
import { computeChallengeId } from "../utils/hmac";
import { asRecord, stringOrUndefined } from "../utils/parsers";

export class CredentialVerifier {
  private readonly secretKey: string;
  private readonly realm: string;

  constructor(config: PluralSellerConfig) {
    this.secretKey = config.challengeSecretKey;
    this.realm = config.realm ?? DEFAULT_REALM;
  }

  /** Decode and validate an `Authorization: Payment <payload>` header. */
  async verify(authorizationHeader?: string): Promise<VerificationResult> {
    const encoded = extractPayload(authorizationHeader ?? "");
    if (!encoded) {
      return { valid: false, error: "Invalid Authorization header format. Expected: Payment <base64url>" };
    }
    let credential: Credential;
    try {
      credential = dictToCredential(decodeJson(encoded));
    } catch {
      return { valid: false, error: "Failed to decode credential from Authorization header" };
    }

    const challenge = credential.challenge;
    if (!challenge.id || !challenge.realm || !challenge.method || !challenge.request) {
      return { valid: false, credential, error: "Credential contains an incomplete challenge" };
    }
    if (challenge.realm !== this.realm) {
      return { valid: false, credential, error: `Challenge realm mismatch. Expected "${this.realm}", got "${challenge.realm}"` };
    }
    if (challenge.method !== "plural") {
      return { valid: false, credential, error: `Unsupported payment method: ${challenge.method}` };
    }
    if (!Number.isFinite(Date.parse(challenge.expires)) || Date.parse(challenge.expires) <= Date.now()) {
      return { valid: false, credential, error: "Challenge has expired" };
    }

    const expectedId = await computeChallengeId(
      this.secretKey,
      challenge.realm,
      challenge.method,
      challenge.intent,
      encodeJson(challenge.request),
      challenge.expires,
    );
    if (challenge.id !== expectedId) {
      return {
        valid: false,
        credential,
        error: "Challenge HMAC verification failed. The challenge was not generated by this server.",
      };
    }
    if (!credential.payload?.token) {
      return { valid: false, credential, error: "Credential missing payment token" };
    }
    return { valid: true, credential };
  }
}

function dictToCredential(raw: unknown): Credential {
  const record = asRecord(raw) ?? {};
  const challenge = asRecord(record.challenge) ?? {};
  const request = asRecord(challenge.request) ?? {};
  const payload = asRecord(record.payload) ?? {};
  return {
    challenge: {
      id: String(challenge.id ?? ""),
      realm: String(challenge.realm ?? ""),
      method: String(challenge.method ?? ""),
      intent: String(challenge.intent ?? ""),
      request: {
        scheme: String(request.scheme ?? ""),
        amount: String(request.amount ?? ""),
        currency: String(request.currency ?? ""),
        resource: String(request.resource ?? ""),
      },
      expires: String(challenge.expires ?? ""),
    } satisfies Challenge,
    source: String(record.source ?? ""),
    payload: {
      type: "token",
      token: String(payload.token ?? ""),
      customer_reference: stringOrUndefined(payload.customer_reference ?? payload.customerReference),
    },
  };
}

function extractPayload(header: string): string | undefined {
  const trimmed = header.trim();
  if (!trimmed.startsWith(PAYMENT_HEADER_PREFIX)) {
    return undefined;
  }
  const payload = trimmed.slice(PAYMENT_HEADER_PREFIX.length).trim();
  return isBase64Url(payload) ? payload : undefined;
}
