import {
  Challenge,
  ChallengeRequest,
  Credential,
  PAYMENT_CREDENTIAL_HEADER,
  PAYMENT_HEADER_PREFIX,
  PaymentGateway,
  PaymentMethod,
  PluralSellerConfig,
  VerificationResult,
} from "../types";
import { decodeJson, encodeJson, isBase64Url } from "../utils/base64url";
import { computeChallengeId } from "../utils/hmac";
import { asRecord, stringOrUndefined } from "../utils/parsers";
import { validateConfig } from "../utils/validation";

export class CredentialVerifier {
  private readonly secretKey: string;
  private readonly realm: string;
  private readonly paymentGateway: PaymentGateway;
  private readonly availablePaymentMethods: PaymentMethod[];

  constructor(config: PluralSellerConfig) {
    validateConfig(config);
    this.secretKey = config.challengeSecretKey;
    this.realm = config.realm ?? config.env;
    this.paymentGateway = config.paymentGateway;
    this.availablePaymentMethods = [...config.availablePaymentMethods];
  }

  /** Decode and validate a `P3P-Credential: Payment <payload>` header value. */
  async verify(credentialHeader?: string): Promise<VerificationResult> {
    const encoded = extractPayload(credentialHeader ?? "");
    if (!encoded) {
      return { valid: false, error: `Invalid ${PAYMENT_CREDENTIAL_HEADER} header format. Expected: Payment <base64url>` };
    }
    let credential: Credential;
    try {
      credential = dictToCredential(decodeJson(encoded));
    } catch {
      return { valid: false, error: `Failed to decode credential from ${PAYMENT_CREDENTIAL_HEADER} header` };
    }

    const challenge = credential.challenge;
    if (!challenge.id || !challenge.realm || !challenge.paymentGateway || !challenge.request) {
      return { valid: false, credential, error: "Credential contains an incomplete challenge" };
    }
    if (challenge.realm !== this.realm) {
      return { valid: false, credential, error: `Challenge realm mismatch. Expected "${this.realm}", got "${challenge.realm}"` };
    }
    if (challenge.paymentGateway !== this.paymentGateway) {
      return { valid: false, credential, error: `Unsupported payment gateway: ${challenge.paymentGateway}` };
    }
    if (!challenge.request.availablePaymentMethods.length) {
      return { valid: false, credential, error: "Challenge missing available payment methods" };
    }
    if (!Number.isFinite(Date.parse(challenge.expires)) || Date.parse(challenge.expires) <= Date.now()) {
      return { valid: false, credential, error: "Challenge has expired" };
    }

    const expectedId = await computeChallengeId(
      this.secretKey,
      challenge.realm,
      challenge.paymentGateway,
      challenge.intent,
      encodeJson(challenge.request),
      challenge.expires,
    );
    if (challenge.id !== expectedId) {
      return {
        valid: false,
        credential,
        error: "Challenge HMAC verification failed. The challenge was not generated by this server.",
      };
    }
    if (!credential.payload?.token) {
      return { valid: false, credential, error: "Credential missing payment token" };
    }
    if (!credential.payload.payment_method) {
      return { valid: false, credential, error: "Credential missing selected payment method" };
    }
    if (
      !challenge.request.availablePaymentMethods.includes(credential.payload.payment_method)
      || !this.availablePaymentMethods.includes(credential.payload.payment_method)
    ) {
      return {
        valid: false,
        credential,
        error: `Selected payment method ${credential.payload.payment_method} is not accepted by this seller challenge`,
      };
    }
    return { valid: true, credential };
  }
}

function dictToCredential(raw: unknown): Credential {
  const record = asRecord(raw) ?? {};
  const challenge = asRecord(record.challenge) ?? {};
  const request = asRecord(challenge.request) ?? {};
  const payload = asRecord(record.payload) ?? {};
  const challengeRequest: ChallengeRequest = {
    scheme: String(request.scheme ?? ""),
    amount: String(request.amount ?? ""),
    currency: String(request.currency ?? ""),
    resource: String(request.resource ?? ""),
    availablePaymentMethods: parsePaymentMethods(request.availablePaymentMethods ?? request.available_payment_methods),
  };
  return {
    challenge: {
      id: String(challenge.id ?? ""),
      realm: String(challenge.realm ?? ""),
      paymentGateway: parsePaymentGateway(challenge.paymentGateway ?? challenge.payment_gateway),
      intent: String(challenge.intent ?? ""),
      request: challengeRequest,
      expires: String(challenge.expires ?? ""),
    } satisfies Challenge,
    source: String(record.source ?? ""),
    payload: {
      type: "token",
      token: String(payload.token ?? ""),
      customer_reference: stringOrUndefined(payload.customer_reference ?? payload.customerReference),
      mobile_number: stringOrUndefined(payload.mobile_number ?? payload.mobileNumber),
      payment_method: parsePaymentMethod(payload.payment_method ?? payload.paymentMethod),
    },
  };
}

function parsePaymentGateway(value: unknown): PaymentGateway {
  return value === PaymentGateway.PineLabsOnline ? PaymentGateway.PineLabsOnline : String(value ?? "") as PaymentGateway;
}

function parsePaymentMethod(value: unknown): PaymentMethod {
  if (value === PaymentMethod.UpiSbmd || value === PaymentMethod.Crypto) {
    return value;
  }
  return String(value ?? "") as PaymentMethod;
}

function parsePaymentMethods(value: unknown): PaymentMethod[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.map(parsePaymentMethod);
}

function extractPayload(header: string): string | undefined {
  const trimmed = header.trim();
  if (!trimmed.startsWith(PAYMENT_HEADER_PREFIX)) {
    return undefined;
  }
  const payload = trimmed.slice(PAYMENT_HEADER_PREFIX.length).trim();
  return isBase64Url(payload) ? payload : undefined;
}
